Bm benchmarking challenge pages
smaht-dac/smaht-portal pull request #199
Opened 2024-07-01 18:58 UTC by Bianca-Morris

**Changelog:**
* Add new section to Data nav for challenge results
* Add COLO829 SNV/Indel V1 Challenge Page + tables

This is viewable on devtest as of July 26th, 2024: https://devtest.smaht.org/data/analysis/colo829-snv-indel-detection

2024-07-01 18:58 UTC, Bianca-Morris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Changes to Navigation - adding Resources Tab](https://trello.com/c/eefwoLPM/291-changes-to-navigation-adding-resources-tab)

2024-07-01 18:59 UTC, Bianca-Morris commented
![](https://github.trello.services/images/mini-trello-icon.png) [COLO829 SNV/Indel Challenge Page](https://trello.com/c/gxMkszyg/295-colo829-snv-indel-challenge-page)

2024-07-31 18:51 UTC, crfmc requested changes
The new page's navigation link has a different width and hover state. It looks like it may be the width of the parent.

![Screenshot 2024-07-31 at 2 43 51 PM](https://github.com/user-attachments/assets/07bac098-d56a-4f26-98b2-ddab42dda52d)

2024-07-31 20:01 UTC, crfmc commented on src/encoded/static/scss/encoded/modules/_static-pages.scss
> +		padding-left: 16px !important;
If overwriting, updating these lines in [_item-pages.scss ](https://github.com/smaht-dac/smaht-portal/blob/9f57189affb2dd87e578a1fbdb2bb9a572fe0e45/src/encoded/static/scss/encoded/modules/_item-pages.scss#L1626-L1628) should do the trick.

```
&[data-first-visible-column=true] {
     padding-left: 0!important;
}
```

2024-08-02 15:33 UTC, Bianca-Morris commented on src/encoded/static/scss/encoded/modules/_static-pages.scss
> +		padding-left: 16px !important;
This should be fixed

2024-08-02 18:13 UTC, crfmc approved these changes

2024-08-05 10:41 UTC, Bianca-Morris commented
This should not be merged as-is currently. The styling for the modal is not appearing for the challenge page at the moment. We'll need to work out a fix for this when I return.

[![Image from Gyazo](https://i.gyazo.com/83f4ef6494b5230a867892bbdda054c9.png)](https://gyazo.com/83f4ef6494b5230a867892bbdda054c9)

2024-08-29 12:56 UTC, merged