Cfm data viz integration
smaht-dac/smaht-portal pull request #23
Opened 2023-10-23 18:46 UTC by crfmc

Associated with [Tello ticket 808](https://trello.com/c/TeLOTr1O/808-d3-visualizations-for-smaht-portal)

- Creates two new static sections (consortium-map and alluvial)
- Adds consortium-map to `/about/consortium/awardees`
- Adds alluvial to `/about/consortium/data`

2023-10-25 19:37 UTC, Bianca-Morris requested changes
Nice work on this! I think you're 99% of the way there... Just a few small details before we call this done:

- Table for the consortium map is overflowing the page. Would be good to get that to have a max of the page width, and have it scroll. (Should be as simple as slapping `.table-responsive` on it.) In the future, we might want to have it default to the table view on mobile devices, or add a two-finger zoom feature to the map, but for now, that should be good enough.
- A few other things in comments

Comments that don't block merge:
- Thinking there might be a way to use one SVG of the map-marker, and then use CSS or D3 to change the fill programmatically. Not a huge issue, but would reduce the number of resources required to load in future.
- I did end up adding a `consortia` and `submission_centers` key/value pair to each of your Static Section inserts when I merged in `ui-dev`. Apparently public/shared pages do not work as expected when this value is not defined. Just a note for the future!

2023-10-25 19:41 UTC, Bianca-Morris commented on src/encoded/tests/data/master-inserts/static_section.json
> +        "title": "Consortium Map",
Specifically the title, by the way. Name can stay the same/is just used for the anchor ID.

2023-10-26 17:54 UTC, crfmc commented on package.json
> -    "@hms-dbmi-bgm/react-workflow-viz": "0.1.5",
Hmm I'm actually not sure when/why this was removed. I'm going to add this back and see if it affects d3.

2023-10-26 18:08 UTC, crfmc commented on CHANGELOG.rst
>  `PR 19: UI-Dev <https://github.com/smaht-dac/smaht-portal/pull/20>`_
Removed. Thanks for explaining!

2023-10-26 18:22 UTC, crfmc commented on src/encoded/static/scss/encoded/modules/_static-pages.scss
> +
Added. Thanks!

2023-10-26 18:33 UTC, crfmc commented on src/encoded/tests/data/master-inserts/static_section.json
> +        "title": "Alluvial",
Adjusted. Thank you!

2023-10-27 17:28 UTC, Bianca-Morris approved these changes

2023-10-27 19:39 UTC, merged